[workspace]
authors = ["Scott Henderson <3924836+scottyhq@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "AWS"
platforms = ["osx-arm64", "linux-aarch64", "linux-64"]
version = "0.1.0"

[tasks]
test = "python earthaccess_test.py"

[dependencies]
earthaccess = ">=0.15.1,<0.16"
xarray = ">=2025.10.1,<2026"
