name: NASA AWS S3 Access
# NOTE: workflow must run in AWS us-west-2
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: runs-on=${{ github.run_id }}/runner=2cpu-linux-arm64
    env:
        #EARTHDATA_TOKEN: ${{ secrets.EARTHDATA_TOKEN }}
        EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
        EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.9.2
        with:
          cache: true
          frozen: true

      - name: Test Access
        run: pixi run test
