name: NASA AWS S3 Access
# NOTE: workflow must run in AWS us-west-2
on:
  workflow_dispatch:
    inputs:
      run-on-aws:
        description: Run on self-hosted AWS runner
        type: boolean
        default: false

jobs:
  test:
    runs-on: ${{ inputs.run-on-aws == true && format('runs-on={0}/runner=2cpu-linux-arm64', github.run_id) || 'ubuntu-latest' }}
    env:
        EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
        EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.9.2
        with:
          cache: true
          frozen: true

      - name: Test Access
        run: pixi run test
