name: Use Self-Hosted AWS Runner
# https://runs-on.com/docs/
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: runs-on=${{ github.run_id }}/runner=2cpu-linux-arm64
    steps:
      - run: echo "Hello from arm64!"
